### PR TITLE
Fix superzone sizing issues. Closes #352

### LINKED ISSUE #352: Get superzone rendering correctly ads bug in progress
The thing wasn't sizing right. Added a callback for when the superzone loads.

### PR DESCRIPTION
**Pull request by jcreamer898**
Needed to make sure the superzone ad could take up all the space it needs.

You can now register callbacks for certain sizes.

### CODE REVIEW

File: src/core/ads/ad_manager.js [hunk 1]
```diff
@@ -25,11 +25,20 @@ export default class AdManager {
...
+    };
+
     this.subscribe();
 
     return this;
   }
 
+  _superzone($unit) {
+    $unit.removeClass("adunit--leaderboard")
+      .addClass("adunit--superzone");;
```
Comment (thomasthesecond) [inline src/core/ads/ad_manager.js]: Double `:`

**Comment by thomasthesecond** [comment]
One thing but :+1:
